### ISSUE TITLE
Decide on an OSS license

### ISSUE THREAD

**Issue by aaronbrighton** [aws-community-projects/aws-organization-for-devs#1]
We need to decide on an OSS license to use for the eventual IaC that will reside in this repository.  This decision can also be used as a starting point / recommendation for future community projects.

Some starting thoughts:

- AWS CDK uses the Apache 2.0 license
- Good comparative chart: [https://choosealicense.com/licenses/](https://choosealicense.com/licenses/)
- According to this source Apache 2.0 is the most frequently used after MIT: [https://www.whitesourcesoftware.com/resources/blog/open-source-licenses-trends-and-predictions/](https://www.whitesourcesoftware.com/resources/blog/open-source-licenses-trends-and-predictions/)
- Some additional info re: Apache 2.0 vs. MIT: [https://www.quora.com/Whats-the-difference-between-Apache-v2-0-and-MIT-license-What-are-the-major-consequences-of-using-Apache-software-over-MIT](https://www.quora.com/Whats-the-difference-between-Apache-v2-0-and-MIT-license-What-are-the-major-consequences-of-using-Apache-software-over-MIT)

My "vote" is for Apache 2.0 license, if anyone else feels differently, please speak up :)

**Comment by michaelbrewer** [comment]
I normally just use MIT

**Comment by Nr18** [comment]
I use MIT for my pet projects. After reading the provided links I realised the license depends on the intent of the project. If the intent is to provide a starting point that people can change to their liking I would go with MIT. Otherwise they need to state in their license file that they altered the Apache 2.0 Licensed code.

Any other thoughts?

**Comment by elthrasher** [comment]
A year is enough time to think about this. I'm going with MIT!
