### ISSUE TITLE
Structuring the organization

### ISSUE THREAD

**Issue by aaronbrighton** [aws-community-projects/aws-organization-for-devs#2]
This may branch out into other topics/issues to help with keeping discussions scoped correctly, this is a starting place for now.

**AWS Control Tower** eliminates a lot of the heavy lifting when it comes to setting up a best-practices adopted organization in AWS, and some of this guidance can be found here: [https://docs.aws.amazon.com/controltower/latest/userguide/aws-multi-account-landing-zone.html](https://docs.aws.amazon.com/controltower/latest/userguide/aws-multi-account-landing-zone.html)

```
When you set up a landing zone, AWS Control Tower performs the following actions in your management account on your behalf:

- Creates two AWS Organizations organizational units (OUs): Security, and Sandbox (optional), contained within the organizational root structure.
- Creates two shared accounts in the Security OU: the Log Archive account and the Audit account.
- Creates a cloud-native directory in AWS SSO, with preconfigured groups and single sign-on access.
- Applies 20 mandatory, preventive guardrails to enforce policies.
- Applies two mandatory, detective guardrails to detect configuration violations.
- Preventive guardrails are not applied to the management account.
- Except for the management account, guardrails are applied to the organization as a whole.
```
_[https://docs.aws.amazon.com/controltower/latest/userguide/how-control-tower-works.html#how-it-works-setup](https://docs.aws.amazon.com/controltower/latest/userguide/how-control-tower-works.html#how-it-works-setup)_

**Creating accounts** and the non-root users to login to user-centric sandbox accounts or shared group project accounts is easy with AWS SSO: [https://docs.aws.amazon.com/controltower/latest/userguide/sso.html](https://docs.aws.amazon.com/controltower/latest/userguide/sso.html)

- There's an opportunity to integrate AWS SSO with other identity sources using SAML, however, it might be advantageous to authenticate users via Slack given community members identities' are tied to a given Slack workspace.  Unfortunately it looks like this is done via OIDC: [https://api.slack.com/authentication/sign-in-with-slack](https://api.slack.com/authentication/sign-in-with-slack).  Maybe some magic/innovation can be done to bridge these technologies?

Because community members have access to AWS Credits for their personal accounts already and there is an opportunity to acquire credits to fund this AWS Organization, we should come up with a rule of what types of workloads can be deployed in this organization.  Some thoughts:

- "Production" workloads that host applications / services used by the community or the public built by the community.
- Development/test workloads for joint community projects -- ideally tied to/deployed from IaC repos here in Github.
- Individual developer specific "sandbox" accounts

**Management account setup** will require a CC, as far as I know we **can** use a prepaid/gift CC.  With application of AWS credits and automated monitoring of billing we can ensure that workloads do not exceed any available AWS credits.

For a simple diagram (**to do** replace with draw.io diagram):

```
                                        [Management Account]
                                                 |
      [Security OU]           |           [Production OU]          |           [Sandbox OU]
            |                                    |                                  |
[Audit Acc] | [Log Acc]                   [x] | [x] | [x]                    [x] | [x] | [x]  
            
```

Additional areas worth discussing:

- IaC, what can be done, what can't?
- What IaC tool should we use?
- Additional Guardrails (SCPs/Config Rules)?
- ?

**Comment by walmsles** [comment]
Just some thoughts on Organization setup and how we can tackle this problem with a layered approach:

1. Start with single account use - secured using best practise - for people new to AWS Cloud to use to secure their accounts which will be of value to the community right away and is the simplest use-case: setup Org with AWS SSO with users
1. Expand to more complex use-cases:  
   1. Billing Account --> Sandbox (simple layered approach)
   1. Billing Account --> sandbox, dev, devops, production

**Comment by walmsles** [comment]
Need to decide if want to automate or just document as well.  Control Tower has no real IaC automation capability right now so again this may become an additional layer - seems choice is Control Tower  (console driven) vs OrgFormation (automated)

**Comment by tobilg** [comment]
Be sure to also have a look at https://github.com/superwerker/superwerker There are existing solutions out there that do more or less exactly this.

**Comment by elthrasher** [comment]
I came across https://github.com/pepperize/cdk-organizations as well, just for completeness. I'm starting with superwerker - wait on a domain to be ready.

**Comment by elthrasher** [comment]
The organization is created via superwerker. There's plenty more to do, but we'll follow up in other issues. I've created `Workloads_Test` and `Workloads_Prod` OUs. Here's the structure to start with:

![Screenshot 2023-03-13 at 7 48 04 AM](https://user-images.githubusercontent.com/1909440/224693405-85cc9c31-7143-409b-8c7c-f3fed9f34c3b.png)
